s/βημα/μεσο
greekdigitalcommunity/greekdigitalcommunity.github.io pull request #12
Opened 2017-10-30 15:47 UTC by thanosIrodotou

2017-10-30 15:54 UTC, smosgr requested changes

2017-10-30 15:54 UTC, smosgr commented on index.html
>            <hr class="my-4">
...στην Ελλάδα και όχι μόνο.

2017-10-31 09:15 UTC, thanosIrodotou commented on index.html
>            <hr class="my-4">
θες οντως τωρα να το αλλαξω και αυτο ρε τρολ? :P 
εντος και εκτος ελλαδος θα βαλω

2017-10-31 09:40 UTC, smosgr commented on index.html
>            <hr class="my-4">
νταξει το 'βαλα εγω ;)

2017-10-31 09:40 UTC, smosgr approved these changes

2017-10-31 12:24 UTC, merged