initial commit - terms
greekdigitalcommunity/greekdigitalcommunity.github.io pull request #15
Opened 2019-06-30 22:53 UTC by kostaspav

2019-06-30 23:12 UTC, smosgr requested changes

2019-06-30 23:12 UTC, smosgr commented on terms.html
> +          <p class="lead">Με στόχο την ομαλή λειτουργία της κοινότητας μας και πάντα με τις αρχές του inclusivity, θέλουμε να δημιουργήσουμε ένα όμορφο περιβάλλον που λειτουργεί για όλους.</p>
inclusivity = συμμετοχικότητα

2019-06-30 23:12 UTC, smosgr commented on terms.html
> +            <li>@<strong>ThanosKorakas</strong> - Θάνος Κορακάς</li>
<li>@<strong>thanos</strong> - Θάνος Ηροδότου</li>

2019-06-30 23:12 UTC, smosgr commented on terms.html
> +          <p>Η ομάδα διαχείρισης παρακολουθεί καθημερινά τις συζητήσεις και εξελίξεις στην κοινότητα του Slack. Εάν αντιμετωπίσετε κάποιο πρόβλημα ή θέλετε να συζητήσετε σχετικά με τους όρους, επικοι
...ή θελετε να συζητήσετε σχετικα με τους όρους, μη διστάσετε να επικοινωνήσετε μαζί μας.

2019-07-01 06:57 UTC, tassoskoutlas commented on terms.html
> +              <a class="nav-link active" href="terms.html">Όροι Χρήσης
Καλύτερα όροι συμμετοχής γιατί είμαστε κοινότητα.

2019-07-01 08:00 UTC, thanos-irodotou commented on terms.html
> +            <li>@<strong>ThanosKorakas</strong> - Θάνος Κορακάς</li>
![unbelievable](https://zippy.gfycat.com/AccurateImpeccableBighornsheep.gif)

2019-07-01 08:23 UTC, kostaspav commented on terms.html
> +          <p class="lead">Με στόχο την ομαλή λειτουργία της κοινότητας μας και πάντα με τις αρχές του inclusivity, θέλουμε να δημιουργήσουμε ένα όμορφο περιβάλλον που λειτουργεί για όλους.</p>
Δεν είμαι σίγουρος ότι πρέπει να το μεταφράσουμε αυτό. Ας το συζητήσουμε πρώτα

2019-07-01 08:23 UTC, kostaspav commented on terms.html
> +          <p>Η ομάδα διαχείρισης παρακολουθεί καθημερινά τις συζητήσεις και εξελίξεις στην κοινότητα του Slack. Εάν αντιμετωπίσετε κάποιο πρόβλημα ή θέλετε να συζητήσετε σχετικά με τους όρους, επικοι
done. Commit incoming.

2019-07-01 08:25 UTC, kostaspav commented on terms.html
> +              <a class="nav-link active" href="terms.html">Όροι Χρήσης
done. Commit incoming.

2019-07-01 08:27 UTC, kostaspav commented on terms.html
> +            <li>@<strong>ThanosKorakas</strong> - Θάνος Κορακάς</li>
done.
Το είχα βάλει στο excel γιατί τα έβλεπα από το member management και χάθηκε στο copy/paste.

2019-07-01 09:04 UTC, thanos-irodotou commented on terms.html
> +              <a class="nav-link" href="https://jobs.greekdigitalcommunity.com" target="_blank">Θέσεις εργασίας</a>
Δε θελει κεφαλαιο `Θ`?

2019-07-01 09:06 UTC, thanos-irodotou commented on terms.html
> +              <a class="nav-link" href="https://jobs.greekdigitalcommunity.com" target="_blank">Θέσεις εργασίας</a>
αν και δε φαινεται να εχει σημασια 🤷‍♂

2019-07-01 09:07 UTC, thanos-irodotou commented on terms.html
> +            <li>@<strong>ThanosKorakas</strong> - Θάνος Κορακάς</li>
ρε αυτο ειναι κεφαλαιο θ? η ειναι και απλα φαινεται σα μικρο στο γκιτχαμπ - Θα τιλταρω 😄 αν δεν ειναι και στους 3 βαλτο κεφαλαιο plz

2019-07-01 09:12 UTC, kostaspav commented on terms.html
> +              <a class="nav-link" href="https://jobs.greekdigitalcommunity.com" target="_blank">Θέσεις εργασίας</a>
Δεν το πείραξα. Ας κάνουμε μικροδιορθώσεις κλπ για άλλα σε διαφορετικό branch και pull request

2019-07-01 09:13 UTC, kostaspav commented on terms.html
> +            <li>@<strong>ThanosKorakas</strong> - Θάνος Κορακάς</li>
![image](https://user-images.githubusercontent.com/2472961/60424701-cfa62180-9be8-11e9-873e-95adf890db3a.png)

2019-07-01 09:13 UTC, kostaspav commented on terms.html
> +            <li>@<strong>ThanosKorakas</strong> - Θάνος Κορακάς</li>
αν ήταν με μικρό θα φαινόταν έτσι
![image](https://user-images.githubusercontent.com/2472961/60424736-e2b8f180-9be8-11e9-93e2-00a5fd685f15.png)

2019-07-01 09:14 UTC, thanos-irodotou commented on terms.html
> +            <li>@<strong>ThanosKorakas</strong> - Θάνος Κορακάς</li>
λολ, κοιτα να δεις κατι πραγματα

2019-07-01 09:18 UTC, thanos-irodotou approved these changes
:shipit: we can always update/fix things later

2019-07-01 09:52 UTC, smosgr approved these changes

2019-07-01 12:34 UTC, merged